# https://circleci.com/docs/2.0/sample-config/#section=configuration
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node
    steps:
      - checkout
      # Restore bundle cache
#      - restore_cache:
#          keys:
#            - rails-demo-{{ checksum "Gemfile.lock" }}
#            - rails-demo-
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - run:
          name: Install dependencies
          command: bundle check || bundle install --jobs 4 --retry 3
#      - save_cache:
#          key: rails-demo-{{ checksum "Gemfile.lock" }}
#          paths:
#            - vendor/bundle
      - run:
          name: Unit Tests
          command: bundle exec rake spec
#      - run:
#          name: Install Link Checker
#          command: npm install blc
#      - run:
#          name: Link Checker
#          command: ./check-links.sh
